import React, { useState, useEffect, useCallback } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import {
  Target,
  CheckCircle2,
  XCircle,
  Award,
  ArrowRight,
  Loader2,
  RotateCcw,
  Sparkles,
  BookOpen,
  AlertTriangle,
  TrendingUp,
  BrainCircuit,
  Compass,
  ChevronRight,
  ShieldCheck
} from 'lucide-react';
import {
  getMyInterventions,
  getNextBestAction,
  getMasteryCheckQuestions,
  submitMasteryCheck
} from '../services/api';
import AIEvidenceBadge from '../components/AIEvidenceBadge';

export default function MasteryCheckPage() {
  const [searchParams] = useSearchParams();
  const conceptParam = searchParams.get('conceptId');
  const interventionParam = searchParams.get('interventionId');

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  
  // Interventions & Current Context
  const [myInterventions, setMyInterventions] = useState([]);
  const [nextBestAction, setNextBestAction] = useState(null);
  const [selectedIntervention, setSelectedIntervention] = useState(null);
  const [selectedConceptId, setSelectedConceptId] = useState(conceptParam || 'concept-parallel-resistance');

  // Questions & Answers
  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState({});
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  const [aiMetadata, setAiMetadata] = useState(null);

  // Load initial data
  const loadData = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const [intRes, nbaRes] = await Promise.all([
        getMyInterventions().catch(() => ({ data: { interventions: [] } })),
        getNextBestAction().catch(() => ({ data: { nextAction: null } }))
      ]);

      const interventions = intRes.data?.interventions || [];
      setMyInterventions(interventions);

      const nba = nbaRes.data?.nextAction || null;
      setNextBestAction(nba);

      // Determine active target concept/intervention
      let activeTarget = null;
      if (interventionParam) {
        activeTarget = interventions.find(i => i.id === interventionParam);
      } else if (nba?.hasActiveAction && nba?.interventionId) {
        activeTarget = interventions.find(i => i.id === nba.interventionId) || {
          id: nba.interventionId,
          conceptId: nba.conceptId,
          conceptName: nba.conceptName,
          preMasteryScore: nba.preMastery,
          misconception: nba.misconception
        };
      } else if (interventions.length > 0) {
        activeTarget = interventions.find(i => i.status === 'pending') || interventions[0];
      }

      if (activeTarget) {
        setSelectedIntervention(activeTarget);
        setSelectedConceptId(activeTarget.conceptId || 'concept-parallel-resistance');
      }

      // Fetch mastery questions for this concept
      const cId = activeTarget?.conceptId || conceptParam || 'concept-parallel-resistance';
      const qRes = await getMasteryCheckQuestions(cId);
      setQuestions(qRes.data?.questions || []);

      // Mastery-check questions are generated by the deterministic curriculum intervention
      // engine — NOT by a live IBM inference call. Accurately marked as curriculum engine.
      setAiMetadata({
        provider: 'curriculum_engine',
        model: 'curriculum-engine-v1',
        latencyMs: qRes.data?._latencyMs || null,
        fallbackUsed: true,
        executionState: 'LOCAL_FALLBACK',
        timestamp: new Date().toISOString()
      });
    } catch (err) {
      console.error('[MasteryCheckPage] Load error:', err);
      setError('Unable to load mastery check questions. Please verify your connection.');
    } finally {
      setLoading(false);
    }
  }, [conceptParam, interventionParam]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // Handle switching interventions / concepts
  const handleSelectIntervention = async (intervention) => {
    setSelectedIntervention(intervention);
    setSelectedConceptId(intervention.conceptId);
    setResult(null);
    setAnswers({});
    setLoading(true);
    try {
      const qRes = await getMasteryCheckQuestions(intervention.conceptId);
      setQuestions(qRes.data?.questions || []);
    } catch (err) {
      console.error('[MasteryCheckPage] Switch error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleAnswerChange = (questionIndex, value) => {
    setAnswers(prev => ({
      ...prev,
      [questionIndex]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    setError('');

    try {
      const formattedAnswers = questions.map((_, idx) => answers[idx] ?? '');
      const payload = {
        interventionId: selectedIntervention?.id || `inv-${Date.now()}`,
        answers: formattedAnswers,
        questions
      };

      const res = await submitMasteryCheck(payload);
      if (res.data?.success) {
        setResult(res.data.result);
        // Mastery-check scoring uses deterministic NLP grading (word-overlap),
        // not a live IBM inference call. Metadata reflects the actual provider.
        setAiMetadata(
          res.data?.result?._aiMetadata || {
            provider: res.data?.result?.gradedByIBM ? 'ibm_watsonx' : 'curriculum_engine',
            model: res.data?.result?.gradedByIBM ? 'ibm/granite-13b-instruct-v2' : 'curriculum-engine-v1',
            latencyMs: res.data?.result?._latencyMs || null,
            fallbackUsed: !res.data?.result?.gradedByIBM,
            executionState: res.data?.result?.gradedByIBM ? 'LIVE_AI' : 'LOCAL_FALLBACK',
            timestamp: new Date().toISOString()
          }
        );
        window.scrollTo({ top: 0, behavior: 'smooth' });
      } else {
        setError(res.data?.message || 'Submission failed.');
      }
    } catch (err) {
      console.error('[MasteryCheckPage] Submit error:', err);
      setError(err.response?.data?.message || 'Error evaluating mastery check.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setAnswers({});
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[500px] space-y-4">
        <Loader2 className="w-8 h-8 text-[#2C4A8F] animate-spin" />
        <p className="text-xs font-mono text-[#141C2B]/70">[ Loading Targeted Mastery Check... ]</p>
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-4xl mx-auto pb-16">
      {/* Page Title & Context */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#141C2B]/15 pb-5">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-0.5 border border-[#2C4A8F]/30 bg-[#2C4A8F]/10 text-[#2C4A8F] text-[10px] font-mono uppercase tracking-wider mb-2">
            <Target className="w-3.5 h-3.5" />
            <span>Closed-Loop Verification Engine</span>
          </div>
          <h1 className="text-3xl font-serif text-[#141C2B] tracking-tight">
            Intervention Mastery <span className="italic text-[#2C4A8F]">Check</span>
          </h1>
          <p className="text-xs text-[#141C2B]/70 font-mono mt-1">
            Prove conceptual recovery after targeted remediation. Every prompt verifies specific curriculum gaps.
          </p>
        </div>

        {/* Provenance Badge */}
        <AIEvidenceBadge metadata={aiMetadata} compact />
      </div>

      {/* Active Intervention Banner */}
      {selectedIntervention && !result && (
        <div className="p-5 stationery-card border border-[#2C4A8F]/30 bg-[#E5DED0] flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <BrainCircuit className="w-4 h-4 text-[#2C4A8F]" />
              <span className="mono-label text-[10px] text-[#2C4A8F]">
                Assigned Learning Gap
              </span>
            </div>
            <h3 className="text-base font-serif font-bold text-[#141C2B]">
              {selectedIntervention.conceptName || selectedIntervention.conceptId}
            </h3>
            {selectedIntervention.misconception && (
              <p className="text-xs font-mono text-rose-800 flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5 text-rose-700 flex-shrink-0" />
                <span>Misconception: {selectedIntervention.misconception}</span>
              </p>
            )}
          </div>

          <div className="flex items-center gap-4 flex-shrink-0 font-mono">
            <div className="text-right">
              <p className="mono-label text-[9px]">Pre-Check Score</p>
              <p className="text-xl font-bold text-rose-800">
                {selectedIntervention.preMasteryScore ?? 43}%
              </p>
            </div>
            <div className="w-px h-8 bg-[#141C2B]/15" />
            <div className="text-left">
              <p className="mono-label text-[9px] text-[#2C4A8F]">Benchmark</p>
              <p className="text-xl font-bold text-emerald-800">≥ 75%</p>
            </div>
          </div>
        </div>
      )}

      {/* Select Different Assigned Interventions */}
      {myInterventions.length > 1 && !result && (
        <div className="flex items-center gap-2 overflow-x-auto pb-2 text-xs">
          <span className="mono-label text-[10px] whitespace-nowrap">
            Assigned Checks:
          </span>
          {myInterventions.map((inv) => (
            <button
              key={inv.id}
              onClick={() => handleSelectIntervention(inv)}
              className={`px-3 py-1 font-mono text-xs whitespace-nowrap transition-all border ${
                selectedIntervention?.id === inv.id
                  ? 'bg-[#141C2B] text-[#EFE9DD] border-[#141C2B]'
                  : 'bg-[#E5DED0] text-[#141C2B]/70 border-[#141C2B]/15 hover:border-[#141C2B]'
              }`}
            >
              [ {inv.conceptName || inv.conceptId} {inv.status === 'completed' && '✓'} ]
            </button>
          ))}
        </div>
      )}

      {/* Error Notice */}
      {error && (
        <div className="p-3.5 bg-rose-500/10 border border-rose-600/30 text-rose-800 text-xs font-mono flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-rose-700 flex-shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* RESULTS DISPLAY */}
      {result ? (
        <div className="space-y-6">
          {/* Hero Recovery Card */}
          <div className="stationery-card p-6 sm:p-8 border border-[#2C4A8F]/30 bg-[#E5DED0] text-center space-y-6">
            <div className="w-14 h-14 border border-[#2C4A8F]/30 bg-[#2C4A8F]/10 flex items-center justify-center mx-auto text-[#2C4A8F]">
              <Award className="w-7 h-7" />
            </div>

            <div className="space-y-2">
              <span className={`inline-block px-3 py-1 text-xs font-mono font-bold border ${
                result.postMastery >= 70
                  ? 'bg-emerald-500/10 text-emerald-800 border-emerald-600/30'
                  : 'bg-amber-500/10 text-amber-800 border-amber-600/30'
              }`}>
                {result.postMastery >= 80 ? 'Mastery Verified' : result.postMastery >= 70 ? 'Competency Achieved' : 'Developing — Further Practice Suggested'}
              </span>
              <h2 className="text-3xl font-serif font-bold text-[#141C2B]">
                {result.recoveryAchieved ? 'Conceptual Recovery Confirmed!' : 'Progress Recorded!'}
              </h2>
              <p className="text-xs font-mono text-[#141C2B]/75 max-w-lg mx-auto leading-relaxed">
                Evidence logged directly into your adaptive Learning Graph. Your instructor dashboard has been notified of this updated competency.
              </p>
            </div>

            {/* Score & Delta Metric Strip */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-2xl mx-auto pt-4 border-t border-[#141C2B]/15">
              <div className="p-4 bg-[#EFE9DD] border border-[#141C2B]/15">
                <p className="mono-label text-[10px]">Pre-Intervention</p>
                <p className="text-2xl font-mono font-bold text-rose-800 mt-1">{result.preMastery}%</p>
              </div>

              <div className="p-4 bg-[#2C4A8F]/10 border border-[#2C4A8F]/30">
                <p className="mono-label text-[10px] text-[#2C4A8F]">Measured Delta</p>
                <div className="flex items-center justify-center gap-1 mt-1 text-2xl font-mono font-bold text-emerald-800">
                  <TrendingUp className="w-5 h-5 text-emerald-700" />
                  <span>+{result.masteryDelta}%</span>
                </div>
              </div>

              <div className="p-4 bg-[#EFE9DD] border border-[#141C2B]/15">
                <p className="mono-label text-[10px]">Post-Check Mastery</p>
                <p className="text-2xl font-mono font-bold text-emerald-800 mt-1">{result.postMastery}%</p>
              </div>
            </div>

            {/* AI Evidence Badge Detailed */}
            <AIEvidenceBadge metadata={aiMetadata} />

            {/* Navigation Actions */}
            <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
              <button
                onClick={handleReset}
                className="btn-outline text-xs flex items-center gap-1.5"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>[ Retake Check ]</span>
              </button>
              <Link
                to="/progress"
                className="btn-filled text-xs flex items-center gap-1.5"
              >
                <span>[ View Learning Graph ]</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>

          {/* Question-by-Question Graded Breakdown */}
          <div className="space-y-4">
            <h3 className="text-sm font-mono uppercase tracking-wider font-bold text-[#141C2B] flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-[#2C4A8F]" />
              <span>Evidence Audit &amp; Citations</span>
            </h3>

            {result.gradedResults?.map((resItem, idx) => (
              <div
                key={resItem.questionId || idx}
                className={`p-5 stationery-card border ${
                  resItem.isCorrect
                    ? 'border-emerald-600/30 bg-[#E5DED0]'
                    : 'border-rose-600/30 bg-[#E5DED0]'
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <div className={`w-7 h-7 flex items-center justify-center flex-shrink-0 mt-0.5 border ${
                      resItem.isCorrect ? 'bg-emerald-500/10 border-emerald-600/30 text-emerald-800' : 'bg-rose-500/10 border-rose-600/30 text-rose-800'
                    }`}>
                      {resItem.isCorrect ? <CheckCircle2 className="w-4 h-4" /> : <XCircle className="w-4 h-4" />}
                    </div>
                    <div>
                      <p className="text-xs font-serif font-bold text-[#141C2B]">{resItem.question}</p>
                      
                      <div className="mt-3 space-y-1 text-xs font-mono">
                        <p className="text-[#141C2B]/70">
                          <span className="font-bold text-[#141C2B]">Your Answer:</span>{' '}
                          <span className={resItem.isCorrect ? 'text-emerald-800 font-bold' : 'text-rose-800 font-bold'}>
                            {resItem.userAnswer || '(blank)'}
                          </span>
                        </p>
                        {!resItem.isCorrect && (
                          <p className="text-[#141C2B]/70">
                            <span className="font-bold text-[#141C2B]">Correct Answer:</span>{' '}
                            <span className="text-emerald-800 font-bold">{resItem.correctAnswer}</span>
                          </p>
                        )}
                      </div>
                    </div>
                  </div>

                  <span className={`px-2 py-0.5 text-[10px] font-mono font-bold border ${
                    resItem.isCorrect ? 'bg-emerald-500/10 text-emerald-800 border-emerald-600/30' : 'bg-rose-500/10 text-rose-800 border-rose-600/30'
                  }`}>
                    {resItem.score} / 5 pts
                  </span>
                </div>

                {resItem.explanation && (
                  <div className="mt-3.5 pt-3 border-t border-[#141C2B]/10 text-xs font-mono text-[#141C2B]/80 bg-[#EFE9DD] p-3 border border-[#141C2B]/10 space-y-1">
                    <p className="mono-label text-[10px] text-[#2C4A8F]">Curriculum Grounding Explanation:</p>
                    <p className="leading-relaxed">{resItem.explanation}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        /* QUESTIONS FORM */
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-6">
            {questions.map((q, idx) => {
              const selectedValue = answers[idx] ?? '';

              return (
                <div
                  key={q.id || idx}
                  className="stationery-card p-6 border border-[#141C2B]/15 bg-[#E5DED0] space-y-4"
                >
                  {/* Question Meta Strip */}
                  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#141C2B]/10 pb-3">
                    <div className="flex items-center gap-2">
                      <span className="w-6 h-6 bg-[#141C2B] text-[#EFE9DD] flex items-center justify-center text-xs font-mono font-bold">
                        {idx + 1}
                      </span>
                      <span className="mono-label text-[10px] bg-[#EFE9DD] border border-[#141C2B]/15 px-2 py-0.5">
                        {q.cognitiveLevel || 'Application'}
                      </span>
                      {q.concept && (
                        <span className="text-[10px] font-mono text-[#141C2B]/60">
                          {q.concept}
                        </span>
                      )}
                    </div>

                    {q.source && (
                      <span className="text-[10px] text-[#2C4A8F] font-mono bg-[#EFE9DD] border border-[#2C4A8F]/30 px-2 py-0.5">
                        {q.source}
                      </span>
                    )}
                  </div>

                  {/* Question Text */}
                  <p className="text-sm font-serif font-bold text-[#141C2B] leading-relaxed">
                    {q.question}
                  </p>

                  {/* Answer Inputs (MCQ, True/False, or Short Answer) */}
                  {q.type === 'mcq' || q.type === 'truefalse' ? (
                    <div className="grid grid-cols-1 gap-2.5 pt-2">
                      {q.options?.map((opt, optIdx) => {
                        const isChosen = selectedValue === opt;
                        const optionLetter = String.fromCharCode(65 + optIdx);

                        return (
                          <label
                            key={optIdx}
                            onClick={() => handleAnswerChange(idx, opt)}
                            className={`flex items-center gap-3 p-3.5 border text-xs font-mono cursor-pointer transition-all ${
                              isChosen
                                ? 'bg-[#141C2B] text-[#EFE9DD] border-[#141C2B]'
                                : 'bg-[#EFE9DD] border-[#141C2B]/15 text-[#141C2B] hover:border-[#141C2B]'
                            }`}
                          >
                            <span className={`w-5 h-5 flex items-center justify-center text-[10px] font-bold border ${
                              isChosen ? 'bg-[#EFE9DD] text-[#141C2B] border-[#EFE9DD]' : 'bg-[#E5DED0] text-[#141C2B] border-[#141C2B]/20'
                            }`}>
                              {optionLetter}
                            </span>
                            <span className="flex-1">{opt}</span>
                          </label>
                        );
                      })}
                    </div>
                  ) : (
                    <div className="pt-2">
                      <textarea
                        rows={3}
                        value={selectedValue}
                        onChange={(e) => handleAnswerChange(idx, e.target.value)}
                        placeholder="Write your explanation grounded in principles..."
                        className="w-full bg-[#EFE9DD] border border-[#141C2B]/20 p-3 text-xs font-mono text-[#141C2B] focus:outline-none focus:border-[#2C4A8F] leading-relaxed"
                      />
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Submit Action */}
          <div className="flex items-center justify-between p-4 stationery-card border border-[#141C2B]/15 bg-[#E5DED0]">
            <p className="text-xs font-mono text-[#141C2B]/70">
              Answered <strong className="text-[#141C2B]">{Object.keys(answers).length}</strong> of{' '}
              <strong className="text-[#141C2B]">{questions.length}</strong> questions
            </p>

            <button
              type="submit"
              disabled={submitting || Object.keys(answers).length === 0}
              className="btn-filled text-xs flex items-center gap-2 py-2 px-5 disabled:opacity-50"
            >
              {submitting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin text-[#EFE9DD]" />
                  <span>[ Evaluating Recovery... ]</span>
                </>
              ) : (
                <>
                  <Target className="w-4 h-4 text-[#EFE9DD]" />
                  <span>[ Submit &amp; Verify Recovery ]</span>
                </>
              )}
            </button>
          </div>
        </form>
      )}
    </div>
  );
}
